### ISSUE TITLE
Implement randomization function for wasm backend

### ISSUE THREAD

**Issue by phated** [noir-lang/aztec_backend#101]
We inject a `random_get` function in the wasm backend but it doesn't generate randomness. We should fix it as it is needed for zero knowledge.

> I think we can merge without it with a tracking issue if this is going to take too much time to fix

_Originally posted by @kevaundray in https://github.com/noir-lang/aztec_backend/pull/84#discussion_r1160099576_

**Comment by TomAFrench** [comment]
Blaine has suggested duplicating this implementation: https://github.com/wasmerio/wasmer/blob/2.3.0/lib/wasi/src/syscalls/mod.rs#L2537
