### ISSUE TITLE
Backend identifier doesn't specify which proving scheme is used

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/aztec_backend#105]
Currently we're identifying this backend as `acvm-backend-barretenberg`:
https://github.com/noir-lang/aztec_backend/blob/c6b50231da065e7550bfe8bddf8e46f4cd8002d7/common/src/crs.rs#L8

I'm a little concerned that this identifier may be not specific enough for situations such as if Barretenberg exposed both turboplonk, ultraplonk (and eventually honk). This naming scheme implies that we'll only ever support one of these modes whereas people could have built applications, etc. which rely on a particular proving scheme.

Seems to me that we should modify this to `acvm-backend-barretenberg-ultraplonk`?

**Comment by phated** [comment]
turboplonk/ultraplonk/etc will be specified with feature flags. When this is finally supported in bb, the way you'll use it should be to pass a single identifier to various functions, so it would be very problematic to duplicate all the code and change one string.
