### ISSUE TITLE
Rename `noir_cache` or use a new location

### ISSUE THREAD

**Issue by phated** [noir-lang/aztec_backend#53]
The `noir_cache` directory is a bit weird, as it's not a dotfile. We should either rename to `.noir_cache` or maybe even put a `noir` entry in `~/.cache` (at least on mac?)

**Comment by TomAFrench** [comment]
Yes, this is something that I've been thinking about as well. We've got 4 different directories for noir/nargo related stuff.

- noirup stores binaries / repo in `~/.nargo`
- ignition string gets stored in `~/noir_cache`
- noir dependency crates are downloaded into `~/nargo` (note this isn't `~/.nargo`
- The stdlib goes in `~/.config/noir-lang/std`

I think we can simplify this quite a bit if we put some thought into where things should live. e.g. Should the stdlib be stored separately to other noir dependencies?
