### ISSUE TITLE
Do not call `get_circuit_size` in StandardComposer constructor

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/aztec_backend#54]
In both the static lib and wasm packges, the `StandardComposer` struct contains both a CRS and Pippenger object. Setting up these objects requires the circuit size (rounded to power of 2 and used by the prover) to fetch the accurate g1 data from the CRS file. We need this Pippenger object to interact with the barretenberg API.

`get_circuit_size` under the hood creates a prover, thus also computing a proving key. We then fetch the rounded circuit size from the prover. However, the `StandardComposer` object is used for all methods interacting with the `barretenberg_wrapper`, meaning we are re-computing the proving key anytime we call `compute_verification_key`, `create_proof_with_pk`, `verify_with_vk`, etc. when we already have a computed proving key. We should remove used of `get_circuit_size`.

There are two possible solutions:

1. We already have the `get_exact_circuit_size` method. This method takes in only a constraint system, constructs a C++ TurboComposer from this constraint system, and then returns the number of gates stored in the composer. This is used for benchmarking circuits, but could replace `get_circuit_size`. We would instead write a method to calculate the rounded circuit size ourselves. We could avoid writing any new C++/barretenberg_wrapper methods by using the existing `get_exact_circuit_size` method.
2. We can have a different StandardComposer constructor that takes in a constraint system and does not set up pippenger and CRS. This composer can be used for compute_proving_key as that method only needs a constraint system. Then we have a separate StandardComposer constructor that takes in a proving key (which compute_verification_key and create_proof_with_pk both require anyway). We have a new method in bb such as get_circuit_size_from_pk that lets us setup pippenger and CRS. For verify_with_vk we take in a verification key which will also give us n , however, we only need g2 which is hardcoded and not reliant on the circuit size. We can have a new CRS method that just gives us the g2 data and use that for verification.

Solution 1. looks to be much more simple and is what I am going to attempt implementing first.

**Comment by phated** [comment]
I believe this was completed by #55
